[package]
name = "brainsurf"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
rfd = "0.15.4"
serde = "1.0.228"
url = "2.5.7"
walkdir = "2.5.0"
